### ISSUE TITLE
Deploy from CLI does not update environment variables

### ISSUE THREAD

**Issue by richardkall** [graphcool/graphcool#799]
**What is the current behavior?**

`graphcool deploy` does not seem to update environment variables correctly. Does not matter if they are defined just as strings or as `${env:NAME}` in `graphcool.yml`.

**How to reproduce:**

1. Clone this Graphcool example and deploy it according to instructions:
https://github.com/graphcool/graphcool/tree/master/examples/env-variables-in-functions

2. Run the query without a parameter and you should see "Hello Alice".

3. Update `NAME` in the `graphcool.yml` file to another string. Re-deploy. The CLI found a diff an deploys.

4. When running the query, "Alice" is still the name, it has not changed.

5. Try changing the string again. A bit unclear what's happening here. I was able to deploy once more, but then `process.env.NAME` seems to be undefined and the query returns "Hello World". I was not able to deploy again after that, even though I'm changing the environment variable no diff is detected.

**What is the expected behavior?**

`graphcool deploy` should detect changes in `functions.hello.handler.code.environment` and update them in the environment.

**CLI version**

graphcool/0.7.0-beta.12 (darwin-x64) node-v8.5.0

**Comment by timsuchanek** [comment]
Thanks for reporting @richardkall !
This is fixed in the latest alpha `graphcool@0.8.0-alpha.8`

**Comment by maxdarque** [comment]
I think I'm still getting this error on `graphcool/0.10.1 (darwin-x64) node-v8.6.0` and I can't seem to update my AWS credentials which is kind of critical

**Comment by marktani** [comment]
As functions are deployed to AWS Lambda, there are certain environment variables that are 'protected', as AWS Lambda writes them. `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are two examples.

**Comment by maxdarque** [comment]
@marktani thanks Nilan. Is there a list of protected environment variables?

Also who's `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` am I seeing when I do a console.log()?
